name: Publish
on:
  workflow_dispatch:
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout gh'
        uses: 'actions/checkout@v2'
        with:
          ref: gh-pages

      - name: 'ls'
        run: 'ls -l'
